export const workMock = [
  {
    id: 1,
    title: 'Gerador de links para o whatsapp',
    description: 'Esta página gera um link direto para iniciar conversas no WhatsApp com um número informado, sem precisar adicioná-lo aos contatos. É ideal para facilitar atendimentos rápidos e agilizar a comunicação.',
    image: '/whats.png',
    techIcons: ['FaHtml5','FaCss3'],
    link: 'https://umrodrigues.github.io/gerar-link-whatsapp/',
  },
  {
    id: 2,
    title: 'Canoas Guitar Shop - Eccomerce',
    description: 'A Canoas Guitar Shop é um e-commerce sediado em Canoas-RS, com layout e configurações desenvolvidos pela Lunaris Tech. Além da parte técnica, a equipe prestou assessoria completa em estratégias de venda online, pagamentos, envios e marketing.',
    image: '/canoasgtshop.png',
    techIcons: [''],
    link: 'https://www.canoasguitarshop.com.br',
  },
  {
    id: 3,
    title: 'Blog - Vip Leilões',
    description: 'A Vip Leilões é uma empresa referência em leilões, neste cliente foi realizado manutenções no blog, o mesmo sendo Wordpress, pontos de seo, tagueamento e outras ferramentas de busca estavam sofrendo problemas. Onde o time da Lunaris Tech realizous as correções.',
    image: '/vipleiloes.png',
    techIcons: ['FaWordpress'],
    link: 'https://blog.vipleiloes.com.br',
  },
  {
    id: 4,
    title: 'E-commerce de Produtos Sustentáveis',
    description: 'Loja online com carrinho de compras, checkout e integração de pagamento.',
    image: '/space.jpg',
    techIcons: ['FaReact', 'SiNextdotjs', 'FaNodeJs'],
    link: 'https://ecommerce-sustentavel.com',
  },
  {
    id: 5,
    title: 'E-commerce de Produtos Sustentáveis',
    description: 'Loja online com carrinho de compras, checkout e integração de pagamento.',
    image: '/space.jpg',
    techIcons: ['FaReact', 'SiNextdotjs', 'FaNodeJs'],
    link: 'https://ecommerce-sustentavel.com',
  },
  {
    id: 6,
    title: 'E-commerce de Produtos Sustentáveis',
    description: 'Loja online com carrinho de compras, checkout e integração de pagamento.',
    image: '/space.jpg',
    techIcons: ['FaReact', 'SiNextdotjs', 'FaNodeJs'],
    link: 'https://ecommerce-sustentavel.com',
  },
];
