export const workMock = [
  {
    id: 1,
    title: 'Gerador de links para o whatsapp',
    description: 'Esta página gera um link direto para iniciar conversas no WhatsApp com um número informado, sem precisar adicioná-lo aos contatos. É ideal para facilitar atendimentos rápidos e agilizar a comunicação.',
    image: '/images/projects/whats.png',
    techIcons: ['FaHtml5','FaCss3'],
    link: 'https://umrodrigues.github.io/gerar-link-whatsapp/',
  },
  {
    id: 2,
    title: 'Canoas Guitar Shop - Eccomerce',
    description: 'A Canoas Guitar Shop é um e-commerce sediado em Canoas-RS, com layout e configurações desenvolvidos pela Lunaris Tech. Além da parte técnica, a equipe prestou assessoria completa em estratégias de venda online, pagamentos, envios e marketing.',
    image: '/images/projects/canoasgtshop.png',
    techIcons: [''],
    link: 'https://www.canoasguitarshop.com.br',
  },
  {
    id: 3,
    title: 'Blog - Vip Leilões',
    description: 'A Vip Leilões é uma empresa referência em leilões, neste cliente foi realizado manutenções no blog, o mesmo sendo Wordpress, pontos de seo, tagueamento e outras ferramentas de busca estavam sofrendo problemas. Onde o time da Lunaris Tech realizous as correções.',
    image: '/images/projects/vipleiloes.png',
    techIcons: ['FaWordpress'],
    link: 'https://blog.vipleiloes.com.br',
  },
  {
  id: 4,
  title: 'Rc Enfermagem',
  description: 'Plataforma institucional da Rc Enfermagem, desenvolvida em Next.js com TypeScript. O projeto está em construção e visa fornecer informações e serviços voltados à área da saúde.',
  image: '/images/projects/rcenf.jpg',
  techIcons: ['FaReact', 'SiNextdotjs'],
  link: 'https://rcenfermagemparavoce.com.br',
},
{
  id: 5,
  title: 'Página de Casamento - Econti',
  description: 'Site personalizado para casamento, feito com Next.js e TypeScript. Permite compartilhar informações do evento com os convidados de forma elegante e moderna.',
  image: '/images/projects/econti-wedding.png',
  techIcons: ['FaReact', 'SiNextdotjs'], 
  link: 'https://casamento.econticomigo.com.br',
},
{
  id: 6,
  title: 'Demolidora LHC',
  description: 'A Demolidora LHC é uma empresa especializada em demolições, terraplanagens e locação de máquinas pesadas. O site foi desenvolvido com HTML e CSS puro, focando em uma apresentação direta e acessível dos serviços oferecidos.',
  image: '/images/projects/lhc.png',
  techIcons: ['FaHtml5', 'FaCss3'],
  link: 'https://www.demolidoralhc.com.br/index.html',
},
{
  id: 7,
  title: 'Br Planejados',
  description: 'Landing page voltado para a venda de imóveis, desenvolvido com Next.js e TypeScript.',
  image: '/images/projects/brplan.jpg',
  techIcons: ['FaReact', 'SiNextdotjs'],
  link: 'https://www.brplanejado.com.br',
},
];

export const workOrder = [7, 4, 3, 2, 5, 6, 1];
